chaos/diod

- configure.ac
- diod.spec.in
- scripts/Makefile.am
- scripts/diod.service.in
Disable the sysv init script and enable this instead.
Fixes issue #11
> init: add systemd service for diod

- utils/diodmount.c
That's what the other mount helpers appear to be doing.
Debian switched to keeping a symlink to /proc/mounts in /etc/mtab, but didn't modify setmntent(3) to handle that case gracefully, so the only way to avoid error messages on Debian systems appears to be to lstat() /etc/mtab and check it's not a symbolic link.
libmount goes further and keeps some mount data in /run/mount/utab or $LIBMOUNT_UTAB, but I don't think we need to do that.
> don't try to update /etc/mtab unless it is a regular file.

- diod/ops.c
Hi,
this (single-character) change fixes a problem for me when exporting through a symlink to a directory on a different file system. If "link" is such a symlink, lstat("link") and lstat("link/file") will have different device ids; that makes diod_walk call _statmnt("link/file"), which tries to stat("link/file/.."), which fails with ENOTDIR:
```
[pid 27405] lstat("/srv/nfs/git/initramfs-tools_0.120_amd64.changes", {st_mode=S_IFREG|0644, st_size=1713, ...}) = 0
[pid 27405] lstat("/srv/nfs/git", {st_mode=S_IFLNK|0777, st_size=13, ...}) = 0
[pid 27405] stat("/srv/nfs/git/initramfs-tools_0.120_amd64.changes", {st_mode=S_IFREG|0644, st_size=1713, ...}) = 0
[pid 27405] stat("/srv/nfs/git/initramfs-tools_0.120_amd64.changes/..", 0x7f13c4fe8a40) = -1 ENOTDIR (Not a directory)
```
I believe the …
> exporting through symlinks/stat vs lstat in diod_walk()

- README.md
- config/ax_lua.m4
- libdiod/diod_conf.c
- libdiod/diod_log.h
- libnpfs/npfs.h
- tests/kern/dbench/Makefile.am
Hi,
These patches solve some compilation issues which the Diod 9p server currently has:
* Eliminating an error when trying to cross-compile a static diod binary. Cross-compiling a statically linked binary may be very useful for embedded or minimalist systems.
* If the Perl binary was not in /usr/bin/perl, the build would fail.
* The build would also fail if Lua 5.2 (and not 5.1) was installed. Deprecated Lua functions replaced.
* Building instructions in README.md were updated.
> Build fixing patches

- diod/Makefile.am
- diod/diod.c
- diod/diod_dir.h
- diod/fid.c
- diod/ioctx.c
- diod/ioctx.h
- diod/ops.c
- diod/xattr.c
- libdiod/diod_auth.c
- libdiod/diod_sock.c
- libnpclient/readdir.c
- libnpfs/fcall.c
- libnpfs/user.c
- deal with lack of dirent.d_off on FreeBSD
- make xattr* functions essentially no-ops
- skip prctl() and setrlimit()
- some differences in struct statfs
- some mount options lacking
- replace SOL_TCP by IPPROTO_TCP
- use linux value for errno EOPNOTSUPP
> FreeBSD port

- diod/ops.c
Error:
diod/ops.c:845: undefined reference to `makedev'
Fixed:
Glibc removes sys/sysmacros.h which defines makedev from sys/types.h
since v2.28. [Commit ID: e16deca62e16f]
And then glibc suggestions us to include <sys/sysmacros.h> directly if
code needs it.
Signed-off-by: Hongzhi.Song <hongzhi.song@windriver.com>
> diod/ops.c: add header file for makedev

- configure.ac
- tests/misc/t10
- tests/user/runtest
- tests/user/tsetxattr.c
- tests/user/txattr.c
- Some test assume the existence of the user daemon with the uid of 1.  Skip
those if the user doesn't exists.
- Recent releases of attr don't ship attr/xattr.h anymore. It's included in
glibc >= 2.27 as sys/xattr.h. Check for sys/xattr.h and use that if it
exists.
> Fix various tests

- diod/ioctx.c
- diod/ioctx.h
- diod/ops.c
- libdiod/diod_sock.c
- tests/user/Makefile.am
- tests/user/t20
- tests/user/t20.exp
- tests/user/testopenfid.c
This is a first attempt at making open-unlink-fstat work (#19, #47). The basic
idea is to extend IOCtx to support stat,chmod/chown/etc. and then simply
delegate to it when the Fid->ioctx is set.
Tests are in `tests/user/t20` `tests/user/testopenfid.c`.
27a5976 is unrelated but required to get tests/misc/t15 pass on my system.
> [rfc] support open-unlink-fstat

- libnpclient/read.c
Don't assume Rread.count is always <= Tread.count.
As far as I can see this only affects `diodcat`.
> libnpclient/read.c: fix out-of-bounds write

- scripts/Makefile.am
systemd.unit(5) states that units of installed packages belong in
`/usr/lib/systemd/system`. `/etc/systemd/system` is reserved for local
configuration (i.e. the administrator).
> Place systemd unit into $(libdir)/systemd/system

- diod.spec.in
- diod/Makefile.am
This PR fixes a build issue when using the spec file. The systemd dependency is required for the build to complete, as well as a removing an extra slash in a Makefile. It would be possible to avoid the hard systemd dependency by using the `%{?systemd_requires}` macro, if you prefer.
The second commit suggests splitting diod in two packages: the main server, diod, and client utilities, such as the mount helper, in diod-utils. Clients don't need to have the diod server running, which is started by default as a post-installation step in the spec file. If that's not desired, I can easily remove the commit.
> Fix systemd build with diod.spec, suggestion to split package in diod{,-utils}

- diod/diod.8.in
- diod/diod.c
- libdiod/diod_sock.c
- utils/diodmount.8.in
- utils/diodmount.c
This allows raw IPv6 addresses to be specified in the command-line arguments to diod and diodmount.  Square brackets are used to specify IPv6 addresses, similar to NFS and socat.
> Support IPv6 addresses

- configure.ac
The README file is empty since the contents were moved to README.md.  I think it was not the intention to have the empty README file still present so this removes it.
> Remove empty README

- diod/diod.8.in
- diod/diod.c
- etc/diod.conf.5.in
- libdiod/diod_conf.c
- libdiod/diod_conf.h
- libdiod/diod_sock.c
- libdiod/diod_sock.h
diod attempts to lookup clients' hostnames with reverse DNS and this
prevents client from connecting if the server does not have working DNS
("diod: getnameinfo: Temporary failure in name resolution").  Add an
option to disable these hostname lookups for systems which do not need
them.
> Add option to disable hostname lookups

- diod/ops.c
- tests/user/t20
- tests/user/t20.exp
As reported in #70, diod doesn't seem to handle a simple ls -l in a v9fs-mounted directory since commit 6749db36c8d297d22083def10c76ea1736a519b4.
This PR reverts that commit and disables an associated test to get us working again.
I don't know if the kernel behavior is wrong or if the [walk(5)](http://man.cat-v.org/plan_9/5/walk) interpretation that motivated the commit and test is wrong, but I am out of time for now, hence this PR.
> allow open+walk to get diod working with linux v9fs again

- libdiod/diod_conf.c
- libdiod/diod_sock.c
- utils/diodmount.8.in
- utils/diodmount.c
These patches make it possible to use the privport option using ipv6.
The also make it possible to specify using privport on cmdline for both diod and diodmount
- For diodmount they do it by adding a new parameter (-p)
- For diod they do it by looking at the content of the -o parameter also together with exports specified with -e parameters. The the privport option can be sent in using -o.
> Use privport with ipv6

- config/ax_compiler_vendor.m4
- config/ax_lua.m4
- configure.ac
- scripts/Makefile.am
1. There was a missing `,` in an `AS_CASE`  in configure.ac 
2. `scripts/Makefile.am` in did not handle separated source and build directories. Replace the local rules with Automake declarations.  This will create the required install, uninstall, and clean operations.
3. Update the m4-files copied from `autoconf-archive`.  Just because I could.
> Build fixes

- libnpfs/conn.c
- libnpfs/ctl.c
- utils/dioddate.c
The members of the timeval struct are both signed (defined by POSIX) and typically both 64 bits on a system where time_t is 64 bits.  This is possible also on 32 bit systems where time_t is larger to handle the 2038 problem.
It's practically impossible to find a type and printf format that works even on all glibc systems.  Play it safe and always use printf with intmax_t and explict int64_t variables for scanf.
Alternatively, we could use autoconf to figure out the sizes and printf format specifiers, but that seemed way to complicated for what we would gain.
Note that I've changes some prints from unsigned to signed, but the data types were always signed anyway and any negative values would probably have resulted in some odd-looking timestamps.
> Handle various time_t sizes in printf and scanf

- tests/kern/Makefile.am
- tests/kern/runtest
- tests/kern/t28
- tests/kern/t33
- tests/user/runtest
- tests/user/t16
Various fixes and workarounds to make the test suite pass in Yocto Project ptest.
I've run these tests on Yocto kernel 6.6.45, which may be why `kern/t31` passes (see #103).
The tests identified in #102, #103, #105, #106 have been added to XFAIL_TESTS.
> test fixes

- diod/diod.c
- libnpfs/conn.c
- libnpfs/npfs.h
- libnpfs/srv.c
Hi,
We have had problems with diod crashing during shutdown and found out that there are races between thread shutdown and data deallocations.
I have made some patches here that I think solves it (at least we cannot trigger the crashes anymore).
> Shutdown cleanup

- diod/xattr.c
- libnpfs/np.c
- tests/misc/t07.exp
- tests/misc/tserialize.c
- tests/user/Makefile.am
- tests/user/t19
- tests/user/t19.exp
- tests/user/tsetxattr_wildoffset.c
This fixes diod's poor (segfaulting) handling of a couple of malformed requests reported by @rtmrtmrtmrtm.
> handle some malformed 9P requests gracefully

- protocol.md
- src/daemon/ops.c
Problem: the remote `fsid` returned in  `Rstatfs` is incorrect.
I botched the construction of `fsid `from `fsid_t f_fsid` (an array of two integers whose size can vary across platforms) when building `Rstatfs`.
Just use `statvfs(3)` instead, which returns `f_fsid` as a single integer.   It's more portable than `statfs(2)` so some ifdefs that cover BSD/linux differences can go away.
Note that `statfs(2)` still has to be called to get the file system type if the `statfs-passthrough` option is configured, but `f_type` seems to be portable across platforms.
> fix incorrect fsid in 9P2000.L statfs response

- etc/diod.conf
- etc/diod.service.in
- man/diod.8.in
- man/diod.conf.5.in
- src/cmd/diod.c
- src/libdiod/diod_conf.c
- src/libdiod/diod_conf.h
- src/libdiod/diod_log.c
- src/libdiod/diod_rdma.c
- src/libdiod/diod_sock.c
- src/libdiod/test/configfile.c
- tests/misc/t15
Since systemd (and probably other pid ones) can manage daemons running in the foreground and capture stderr, drop diod's capability to daemonize and log to syslog to keep things simple.
As a bonus it avoid the unexpected WTF? when you manually run`diod` and nothing apparently happens (because it backgrounded itself).
> diod: do not daemonize, do not syslog

- etc/diod.service.in
- src/cmd/diod.c
- src/libdiod/diod_log.c
- src/libdiod/diod_rdma.c
- src/libdiod/diod_sock.c
- src/libtest/server.c
- tests/misc/Makefile.am
- tests/misc/t15
The systemd unit file is modified so that `systemctl reload diod` can be used to modify the exports config without completely restarting.
In addition, this tweaks logging slightly
- TAP tests log with  "# " prefix
- diod server logs without a program prefix
- listen addresses are now logged on startup
> enable systemctl reload diod + minor logging improvements

- configure.ac
- src/cmd/Makefile.am
- src/cmd/diod.c
- src/libdiod/Makefile.am
- src/libdiod/diod_auth.c
- src/libnpclient/Makefile.am
- src/libnpfs/Makefile.am
- src/libnpfs/test/capability.c
- src/libnpfs/user-linux.c
- tests/kern/Makefile.am
- tests/user/Makefile.am
This tidies up the initialization code in the diod mainline and causes some of its critical choices to be logged so it's more obvious how it will be operating.   For example, `systemd status diod` shows the following on my system:
```
$ systemctl status diod
● diod.service - 9P File Server
Loaded: loaded (/lib/systemd/system/diod.service; enabled; vendor preset: enable>
Active: active (running) since Mon 2025-01-20 19:17:11 PST; 12min ago
Main PID: 3914040 (diod)
Tasks: 10 (limit: 76971)
Memory: 664.0K
CPU: 2ms
CGroup: /system.slice/diod.service
└─3914040 /usr/sbin/diod
Jan 20 19:17:11 system76-pc systemd[1]: Starting 9P File Server...
Jan 20 19:17:11 system76-pc systemd[1]: Started 9P File Server.
Jan 20 19:17:11 system76-pc diod[3914040]: Listening on 0.0.0.0:564
Jan 20 19:17:11 …
```
> tighten up diod configuration and initialization

- src/cmd/diod.c
Commit 3dc9363f7bf8 ("diod: always run in the foreground") did what it says on the tin and removed the functionality to daemonize. The old --foreground option that disabled daemonization was also removed.
The breaks existing setups that were using foreground execution all along via passing --foreground: The option no longer exists and instead the full usage test is printed.
As not to break existing setups, let's keep the --foreground option around for now and just make it a no-op, given that it became the default behavior.
> diod: keep --foreground option for compatibility

- src/libnpfs/fcall.c
The check here is skipped if diod receives Tread or Twrite with a count greater than UINT32_MAX - IOHDRSZ (4294967271). This eventually trips an assert in np.c.
Let's just cast the incoming size to 64-bits before doing any math that may lead to an overflow.
I encountered this after forgetting to properly bound a read size.
> diod: Fix uint32 overflow when Tread/Twrite count > UINT32_MAX-IOHDRSZ

- src/libdiod/diod_ops.c
- src/libnpfs/fcall.c
- src/libnpfs/npfs.h
- src/libnpfs/protocol.h
Implements Tunlinkat and Trenameat, ironically not using either of those syscalls.
> Implement Trenameat and Tunlinkat
